# Generated by Django 6.0.5 on 2026-05-18 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(choices=[('PADEIRO', 'Padeiro'), ('ATENDENTE', 'Atendente'), ('GERENTE', 'Gerente'), ('OUTRO', 'Outro')], max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=300)),
                ('contato_emergencia', models.CharField(blank=True, max_length=200)),
                ('data_admissao', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('em_ferias_ate', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ATESTADO', 'Atestado médico'), ('LICENCA', 'Licença'), ('FERIAS', 'Férias'), ('OUTRO', 'Outro')], max_length=12)),
                ('titulo', models.CharField(max_length=120)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='atestados/')),
                ('nome_arquivo', models.CharField(blank=True, max_length=200)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='funcionarios.funcionario')),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('origem', models.CharField(default='manual', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='funcionarios.funcionario')),
            ],
            options={
                'ordering': ['-data', '-hora'],
            },
        ),
    ]
