# Generated by Django 6.0.5 on 2026-05-18 17:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo_barras', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('unidade', models.CharField(choices=[('PESO', 'Peso (kg)'), ('UNIDADE', 'Unidade')], default='UNIDADE', max_length=10)),
                ('descricao', models.TextField(blank=True)),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.categoria')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('motivo', models.CharField(choices=[('VENDA', 'Venda'), ('CANCELAMENTO', 'Cancelamento de venda'), ('AJUSTE', 'Ajuste manual'), ('ENTRADA', 'Entrada de estoque')], max_length=20)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='produtos.produto')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
