# Generated by Django 6.0.5 on 2026-05-18 17:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=300)),
                ('negativado', models.BooleanField(default=False)),
                ('score_serasa', models.PositiveIntegerField(blank=True, null=True)),
                ('restricoes_serasa', models.PositiveSmallIntegerField(default=0)),
                ('ultima_consulta_serasa', models.DateTimeField(blank=True, null=True)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente_desde', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
